FROM pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
COPY src/ ./src/
COPY flask_app/ ./flask_app/

RUN useradd -m -u 50000 appuser && \
    usermod -aG video appuser && \
    chown -R 50000:0 /app

USER appuser

ENV PYTHONPATH=/app/src

CMD ["python", "flask_app/app.py"]