# dvc.yaml
stages:
  prepare_data:
    cmd: bash scripts/prepare_data.sh ${prepare.dataset_name}
    deps:
      - data/${prepare.dataset_name}
      - src/config.py
      - src/prepare_data.py
    outs:
      - data/${prepare.dataset_name}_baseline_stats.json
      - data/${prepare.dataset_name}_manifest.json
      - data/${prepare.dataset_name}_data_metrics.json:
          cache: false
    # metrics:
    #   - data/${prepare.dataset_name}_data_metrics.json:
    #       cache: false

  train:
    cmd: bash scripts/train.sh ${prepare.dataset_name}
    deps:
      - data/${prepare.dataset_name}_manifest.json
      - data/${prepare.dataset_name}_data_metrics.json
      - src/config.py
      - src/dataloader.py
      - src/model.py
      - src/sweep_optuna.py
      - src/train.py
      - src/utils.py
      - scripts/train.sh
    params:
      - train
    outs:
      - checkpoints/${prepare.dataset_name}_best_run.json
    metrics:
      - checkpoints/${prepare.dataset_name}_dvc_metrics.json:
          cache: false

  register:
    cmd: bash scripts/register.sh ${prepare.dataset_name}
    deps:
      - checkpoints/${prepare.dataset_name}_best_run.json
      - src/register_model.py
    outs:
      - checkpoints/${prepare.dataset_name}_registered_version.txt